title: <p align="center"> Nithin Rajidi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nithin-rajidi/">LinkedIn</a> |
  <a href="https://github.com/nithin399">GitHub</a>
  
  <br>   
  I'm working on consultant
 
  <br>
  </p>



theme: jekyll-theme-minimal
